[
  {
    "allowed_users": {
      "1": {
        "username": "test_maxus",
        "password": "ABC_HAX"
      },
      "2": {
        "username": "trojan",
        "password": "hacks"
      },
      "3": {
        "username": "keylogger",
        "password": "hacker_man"
      }
    },
  },
  {
    "filler": 1234567890,
    "a": "A",
    "b": "B",
    "c": "C",
    "d": "D",
    "e": "E"
  },
  {
    "illegal_users": {
      "username": "password",
      "admin": "admin",
      "0000": "0000",
      "any1": "password",
      "any2": "123",
      "any3": "123456",
      "ESCAPE": "CONTROL",
      "MEME": "DUNGEON",
      "MD": "MD",
      "maxus": "maxus",
      "any4": "admin",
      "gg": "wp",
      "trojan": "trojan",
      "any5": "trojan",
      "encoded": "decoded",
      "any6": "comment"
    },
    "banned_users": {
      "any1": "yo_mama",
      "any2": "1234567890"
    }
  },
  "userdata_bin_encoded",
  "userdata_b64_encoded",
  "anti_b64_key_finder",
  "anti_bin_getter",
  "anti_rat_protection",
  "javaw2048M_loader",
  "System.getProperty(\"user.dir\")",
  {
    "ALPHABETTO": {
      "signature": "ab.sgr",
      "encoding_type": "BASE64_MODIFIED",
      "ab_version": "ab.ver",
      "ab_decoder": "BASE64_ABM_DECODE",
      "anti_rat": true,
      "anti_decoder": false,
      "rearranger_key": "base64_ab"
    }
  },
  "IDE_FALSE",
  {
    "trojan_active": true,
    "hyperion": false,
    "epsilon": true,
    "keylogger": true,
    "rat": true,
    "antivirus_invisibility": true
  }
]